# -------
# profile
# -------
name: ktrysmt.github.io
description: Blogging about Web Development from Japan
meta_description: "ktrysmt.github.io, Blogging about Web Development from Japan."
github: https://www.github.com/ktrysmt
about: I am a web developer from Tokyo, Japan.
urls:
  - text: 'Category List'
    url: /category/
  - text: Github
    url: https://github.com/ktrysmt 
author: 'Kotaro Yoshimatsu <kotaro.yoshimatsu@gmail.com>'
url: https://ktrysmt.github.io/
#avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png 
 
# --------
# settings
# --------
markdown: kramdown
highlighter: rouge
logo: false
paginate: 9999
permalink: /:title/
baseurl: /
domain_name: 'https://ktrysmt.github.io/'
gems: 
  - jekyll-paginate
  - jekyll-sitemap 
#google_analytics: 'UA-XXXXXXXX-X'


  


