name: ktrysmt.github.io
url: https://ktrysmt.github.io/
github: https://www.github.com/ktrysmt
about: I am a web developer from Tokyo, Japan.
urls:
    - text: 'Category List'
      url: /category/
    - text: Github
      url: https://github.com/ktrysmt
markdown: kramdown
highlighter: rouge
permalink: /:title/
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
